my_toolbox:
  display:
    always:
      - track_info
    if_var:
      DEBUG:
        - track_time

  on_error:
    always:
      - handle_problem

  log_output:
    if_var:
      DEBUG:
        - terminal
    if_not_var:
      DEBUG:
        - file
