my_toolbox:
  hooks:
    always:
      - track_info
    if_var:
      DEBUG:
        - track_time
  wrappers:
    always:
      - retry
  sinks:
    if_var:
      DEBUG:
        - terminal
    if_not_var:
      DEBUG:
        - file

error_toolbox:
  hooks:
    always:
      - handle_problem
