"""`python -m ping` — curate ping's target list (the autogenerated JSON).

The CLI only edits data: which functions/files ping watches and whether it's on.
What ping *does* on a match is the separate `ping.yaml` config; the running app
picks up edits here on its next call (mtime-reloaded), no restart.
"""

import argparse
import json
import os
from pathlib import Path

_PING_DIR = Path(__file__).resolve().parent
_TARGETS = _PING_DIR / "config" / "targets.json"
_CONFIG = _PING_DIR / "config" / "ping.yaml"


def _load():
    try:
        with open(_TARGETS) as fh:
            return json.load(fh) or {}
    except (OSError, ValueError):
        return {}


def _save(data):
    _TARGETS.parent.mkdir(parents=True, exist_ok=True)
    with open(_TARGETS, "w") as fh:
        json.dump(data, fh, indent=2)
        fh.write("\n")


def _classify(target):
    return "files" if target.endswith(".py") or os.sep in target else "functions"


def cmd_init(args):
    data = _load()
    data.setdefault("functions", [])
    data.setdefault("files", [])
    data.setdefault("enabled", True)
    _save(data)
    print(f"ping: initialized {_TARGETS}")
    return 0


def cmd_add(args):
    data = _load()
    key = _classify(args.target)
    value = os.path.abspath(args.target) if key == "files" else args.target
    items = data.setdefault(key, [])
    if value in items:
        print(f"ping: {value} already targeted")
        return 0
    items.append(value)
    data.setdefault("enabled", True)
    _save(data)
    print(f"ping: added {key[:-1]} {value}")
    return 0


def cmd_rm(args):
    data = _load()
    candidates = {args.target, os.path.abspath(args.target)}
    removed = False
    for key in ("functions", "files"):
        kept = [i for i in data.get(key, []) if i not in candidates]
        if len(kept) != len(data.get(key, [])):
            data[key] = kept
            removed = True
    if removed:
        _save(data)
        print(f"ping: removed {args.target}")
    else:
        print(f"ping: {args.target} not found")
    return 0


def cmd_list(args):
    data = _load()
    print(f"enabled: {data.get('enabled', True)}")
    for key in ("functions", "files"):
        print(f"{key}:")
        for item in data.get(key, []):
            print(f"  {item}")
    return 0


def cmd_clear(args):
    data = _load()
    data["functions"] = []
    data["files"] = []
    _save(data)
    print("ping: cleared targets")
    return 0


def cmd_on(args):
    data = _load()
    data["enabled"] = True
    _save(data)
    print("ping: on")
    return 0


def cmd_off(args):
    data = _load()
    data["enabled"] = False
    _save(data)
    print("ping: off")
    return 0


def cmd_status(args):
    data = _load()
    n = len(data.get("functions", [])) + len(data.get("files", []))
    print(f"ping: {'on' if data.get('enabled', True) else 'off'}, {n} target(s)")
    print(f"config:  {_CONFIG}")
    print(f"targets: {_TARGETS}")
    return 0


def build_parser():
    parser = argparse.ArgumentParser(prog="ping", description="curate ping's dev diagnostic targets")
    sub = parser.add_subparsers(dest="cmd", required=True)
    sub.add_parser("init", help="create an empty targets file").set_defaults(func=cmd_init)
    add = sub.add_parser("add", help="watch a function (pkg.mod.func) or file (path.py)")
    add.add_argument("target")
    add.set_defaults(func=cmd_add)
    rm = sub.add_parser("rm", help="stop watching a target")
    rm.add_argument("target")
    rm.set_defaults(func=cmd_rm)
    sub.add_parser("list", help="show all targets").set_defaults(func=cmd_list)
    sub.add_parser("clear", help="remove all targets").set_defaults(func=cmd_clear)
    sub.add_parser("on", help="enable matching").set_defaults(func=cmd_on)
    sub.add_parser("off", help="disable matching").set_defaults(func=cmd_off)
    sub.add_parser("status", help="show state").set_defaults(func=cmd_status)
    return parser


def main(argv=None):
    args = build_parser().parse_args(argv)
    return args.func(args)
